/**
 * Professional PDF rendering for referral partnership agreements.
 * Uses measured word-wrapping to avoid overlapping text and awkward breaks.
 */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

const DRAFT_BANNER = 'DRAFT — NOT FOR SIGNATURE'

export function htmlToPlainText(html) {
  return String(html || '')
    .replace(/<hr\s*\/?>/gi, '\n\n—\n\n')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<\/h[1-6]>/gi, '\n\n')
    .replace(/<\/li>/gi, '\n')
    .replace(/<li[^>]*>/gi, '• ')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

function stripDraftArtifacts(text) {
  return String(text || '')
    .split('\n')
    .filter((line) => {
      const t = line.trim()
      if (!t) return true
      if (t.includes('DRAFT — NOT FOR SIGNATURE')) return false
      if (t.includes('DRAFT — LEGAL REVIEW REQUIRED')) return false
      if (/Generated by Aurora Sonnet CRM/i.test(t)) return false
      if (/Do not send for signature or activate/i.test(t)) return false
      if (/not legal advice/i.test(t)) return false
      if (/Owner Approval is required/i.test(t)) return false
      return true
    })
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

function wrapParagraph(text, font, fontSize, maxWidth) {
  const words = String(text).split(/\s+/).filter(Boolean)
  if (!words.length) return ['']
  const lines = []
  let line = ''
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word
    const width = font.widthOfTextAtSize(candidate, fontSize)
    if (width > maxWidth && line) {
      lines.push(line)
      line = word
    } else {
      line = candidate
    }
  }
  if (line) lines.push(line)
  return lines
}

function layoutBlocks(rawText, font, fontSize, maxWidth) {
  const paragraphs = String(rawText).split(/\n\n+/)
  const lines = []
  for (const para of paragraphs) {
    const trimmed = para.trim()
    if (!trimmed) {
      lines.push({ text: '', kind: 'blank' })
      continue
    }
    const isHeading =
      /^Referral Partnership Agreement/i.test(trimmed) ||
      /^Commercial Terms/i.test(trimmed) ||
      /^\d+\.\s/.test(trimmed) ||
      /^DRAFT —/.test(trimmed)
    const wrapped = wrapParagraph(trimmed.replace(/\n+/g, ' '), font, fontSize, maxWidth)
    for (let i = 0; i < wrapped.length; i++) {
      lines.push({ text: wrapped[i], kind: isHeading && i === 0 ? 'heading' : 'body' })
    }
    lines.push({ text: '', kind: 'blank' })
  }
  while (lines.length && lines[lines.length - 1].kind === 'blank') lines.pop()
  return lines
}

export async function renderAgreementPdfFromHtml(contentHtml, { includeDraftBanner = false } = {}) {
  let text = htmlToPlainText(contentHtml)
  if (!includeDraftBanner) {
    text = stripDraftArtifacts(text)
  } else if (!text.includes(DRAFT_BANNER)) {
    text = `${DRAFT_BANNER}\n\n${text}`
  }

  const pdf = await PDFDocument.create()
  const regular = await pdf.embedStandardFont(StandardFonts.Helvetica)
  const bold = await pdf.embedStandardFont(StandardFonts.HelveticaBold)
  const bodySize = 10
  const headingSize = 11
  const bannerSize = 14
  const lineHeight = 14
  const headingGap = 6
  const margin = 54
  const pageWidth = 612
  const pageHeight = 792
  const maxWidth = pageWidth - margin * 2

  const layout = layoutBlocks(text, regular, bodySize, maxWidth)
  let page = pdf.addPage([pageWidth, pageHeight])
  let y = pageHeight - margin

  const newPageIfNeeded = (needed = lineHeight) => {
    if (y - needed < margin) {
      page = pdf.addPage([pageWidth, pageHeight])
      y = pageHeight - margin
    }
  }

  for (const row of layout) {
    if (row.kind === 'blank') {
      y -= lineHeight * 0.55
      continue
    }
    const isBanner = row.text.includes(DRAFT_BANNER)
    const isHeading = row.kind === 'heading' && !isBanner
    const size = isBanner ? bannerSize : isHeading ? headingSize : bodySize
    const font = isBanner || isHeading ? bold : regular
    const gap = isHeading ? headingGap : 0
    newPageIfNeeded(lineHeight + gap)
    if (gap) y -= gap
    page.drawText(row.text, {
      x: margin,
      y,
      size,
      font,
      color: rgb(0.12, 0.1, 0.08),
    })
    y -= lineHeight + (isBanner ? 4 : 0)
  }

  const pages = pdf.getPages()
  if (pages.length > 1) {
    const last = pages[pages.length - 1]
    const minContentY = margin + lineHeight * 2
    let lastContentY = margin
    // If last page is nearly empty, merge by removing it (simple heuristic: only banner/footer residue)
    const lastText = layout.slice(-8).map((l) => l.text).join(' ')
    if (lastText.trim().length < 40 && pages.length > 2) {
      pdf.removePage(pages.length - 1)
    } else if (y > pageHeight - margin - lineHeight * 4 && pages.length > 1) {
      // orphan guard: already handled by layout; no-op
      void lastContentY
      void last
      void minContentY
    }
  }

  return Buffer.from(await pdf.save())
}

export { DRAFT_BANNER, stripDraftArtifacts }
